#!/bin/bash
set -e

read FILE
read LINE_NO
TIME=$(date +%H:%M:%S)
SEC=$(date +%S)
#echo "$TIME"

LOREM=(LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISCING ELIT EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA UT ENIM AD MINIM VENIAM QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EA COMMODO CONSEQUAT DUIS AUTE IRURE DOLOR REPREHENDERIT VOLUPTATE VELIT ESSE CILLUM DOLORE EU FUGIAT NULLA PARIATUR EXCEPTEUR SINT OCCAECAT CUPIDATAT NON PROIDENT SUNT CULPA QUI OFFICIA DESERUNT MOLLIT ANIM EST LABORUM)

sed -i -e "${LINE_NO}s/^/${TIME} ${LOREM[$SEC]} ${LOREM[$SEC+1]}NL/g" $FILE
sed -i -e 's/NL/\
/g' $FILE

LOREM1=${LOREM[$SEC]}
LOREM2=${LOREM[$SEC+1]}

git commit -am "automate2.sh adding \`$TIME $LOREM1 $LOREM2\` to line $LINE_NO of $FILE"
#
##git pull-request

