name: Checks
on: 
  - pull_request
jobs:
  cat:
    runs-on: ubuntu-latest
    steps:
      # Need to checkout the base ref, so we have something to compare to
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - uses: actions/checkout@v2
      - run: yarn
      - name: Run ESLint
        uses: Khan/eslint-action@main
        with:
          eslint-lib: ./node_modules/eslint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Flow
        uses: Khan/flow-action@v1.1.2
        with:
          flow-bin: ./node_modules/.bin/flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Jest
        uses: Khan/jest-action@v1.1.4
        with:
          jest-bin: ./node_modules/.bin/jest
          find-related-tests: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
